server:
  port: 8083

# 服务名称
spring:
  application:
    name: hystrix

# Eureka 服务器地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  circuitbreaker:
    enabled: true

# 配置监控端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, prometheus, health, info
